package com.d3v4d.receiptscanner.service

import com.d3v4d.receiptscanner.dto.request.ReceiptLineRequestDTO
import com.d3v4d.receiptscanner.dto.request.ReceiptRequestDTO
import com.d3v4d.receiptscanner.dto.request.Store
import com.d3v4d.receiptscanner.dto.response.CategoryResponseDTO
import com.d3v4d.receiptscanner.dto.response.ReceiptLineResponseDTO
import com.d3v4d.receiptscanner.dto.response.ReceiptResponseDTO
import com.d3v4d.receiptscanner.entity.ReceiptEntity
import com.d3v4d.receiptscanner.entity.ReceiptItemEntity
import com.d3v4d.receiptscanner.entity.StoreEntity
import com.d3v4d.receiptscanner.entity.UserEntity
import java.time.Instant
import java.time.LocalDate
import java.time.LocalDateTime
import java.time.OffsetDateTime
import java.time.ZoneOffset
import java.time.format.DateTimeFormatter
import java.time.format.DateTimeParseException

fun ReceiptEntity.toDTO(): ReceiptResponseDTO {
    return ReceiptResponseDTO(
        id = this.id,
        sourceScanId = this.sourceScan?.id,
        storeName = this.store?.name ?: "",
        storeAddress = this.store?.address ?: "",
        storeTaxNumber = this.store?.taxNumber ?: "",
        storeChain = this.store?.storeChain ?: "",
        purchaseDateTime = this.purchaseDateTime.toString(),
        total = this.total,
        paymentMethod = this.paymentMethod,
        currency = this.currency,
        lines = this.lines.map { it.toDTO() }
    )
}

fun ReceiptItemEntity.toDTO(): ReceiptLineResponseDTO {
    return ReceiptLineResponseDTO(
        id = this.id,
        name = this.name,
        quantity = this.quantity.toString(),
        unit = this.unit,
        unitPrice = this.unitPrice,
        category = this.category?.let { 
            CategoryResponseDTO(
                id = it.id,
                name = it.name,
                description = it.description,
            )
        },
    )
}

fun ReceiptRequestDTO.toEntity(
    user : UserEntity,
    id: Long = 0,
): ReceiptEntity {
    val receipt = ReceiptEntity(
        id = id,
        purchaseDateTime = parsePurchaseDateTime(this.purchaseDateTime),
        currency = this.currency,
        total = this.total,
        paymentMethod = this.paymentMethod,
        lines = mutableListOf(),
        user = user,
        store = this.store.toEntity(),
    )

    receipt.lines = this.lines.map { dto ->
            dto.toEntity(receipt)
        }
        .toMutableList()

    return receipt
}


fun ReceiptLineRequestDTO.toEntity(
    receipt: ReceiptEntity,
) : ReceiptItemEntity {
    return ReceiptItemEntity(
        id = 0, // ID will be generated by the database
        name = this.name,
        quantity = this.quantity,
        unit = this.unit,
        unitPrice = this.unitPrice,
        totalPrice = this.totalPrice,
        receipt = receipt,
    )
}

fun Store.toEntity(): StoreEntity {
    return StoreEntity(
        name = this.name,
        address = this.address,
        taxNumber = this.taxNumber.toString(),
        storeChain = this.chain,
    )
}

private fun parsePurchaseDateTime(value: String): Instant {
    val trimmed = value.trim()
    if (trimmed.isEmpty()) {
        throw IllegalArgumentException("purchase_datetime is required")
    }

    try {
        return Instant.parse(trimmed)
    } catch (_: DateTimeParseException) {
    }

    try {
        return OffsetDateTime.parse(trimmed).toInstant()
    } catch (_: DateTimeParseException) {
    }

    val localDateTimePatterns = listOf(
        DateTimeFormatter.ISO_LOCAL_DATE_TIME,
        DateTimeFormatter.ofPattern("yyyy-MM-dd HH:mm:ss"),
        DateTimeFormatter.ofPattern("yyyy-MM-dd HH:mm"),
        DateTimeFormatter.ofPattern("yyyy.MM.dd HH:mm:ss"),
        DateTimeFormatter.ofPattern("yyyy.MM.dd HH:mm"),
        DateTimeFormatter.ofPattern("dd.MM.yyyy HH:mm:ss"),
        DateTimeFormatter.ofPattern("dd.MM.yyyy HH:mm"),
    )

    for (formatter in localDateTimePatterns) {
        try {
            return LocalDateTime.parse(trimmed, formatter).toInstant(ZoneOffset.UTC)
        } catch (_: DateTimeParseException) {
        }
    }

    val localDatePatterns = listOf(
        DateTimeFormatter.ISO_LOCAL_DATE,
        DateTimeFormatter.ofPattern("yyyy.MM.dd"),
        DateTimeFormatter.ofPattern("dd.MM.yyyy"),
    )

    for (formatter in localDatePatterns) {
        try {
            return LocalDate.parse(trimmed, formatter).atStartOfDay().toInstant(ZoneOffset.UTC)
        } catch (_: DateTimeParseException) {
        }
    }

    throw IllegalArgumentException(
        "Invalid purchase_datetime '$value'. Use ISO instant (e.g. 2026-04-20T10:15:30Z) or a common date/date-time format.",
    )
}

