package com.d3v4d.receiptscanner.service

import com.d3v4d.receiptscanner.dto.request.ReceiptLineRequestDTO
import com.d3v4d.receiptscanner.dto.request.ReceiptRequestDTO
import com.d3v4d.receiptscanner.dto.response.ReceiptLineResponseDTO
import com.d3v4d.receiptscanner.dto.response.ReceiptResponseDTO
import com.d3v4d.receiptscanner.entity.ProductEntity
import com.d3v4d.receiptscanner.entity.ReceiptEntity
import com.d3v4d.receiptscanner.entity.ReceiptLineEntity
import com.d3v4d.receiptscanner.entity.UserEntity
import java.time.Instant

fun ReceiptEntity.toDTO(): ReceiptResponseDTO {
    return ReceiptResponseDTO(
        id = this.id,
        storeName = this.storeName,
        purchaseDateTime = this.purchaseDateTime.toString(),
        currency = this.currency,
        lines = this.lines.map { it.toDTO() }
    )
}

fun ReceiptLineEntity.toDTO(): ReceiptLineResponseDTO {
    return ReceiptLineResponseDTO(
        id = this.id,
        name = product?.name ?: rawName,
        quantity = this.quantity.toString(),
        unit = this.unit,
        unitPrice = this.unitPrice,
    )
}

fun ReceiptRequestDTO.toEntity(
    user : UserEntity,
    id: Long = 0,
    products : List<ProductEntity>,
): ReceiptEntity {
    val receipt = ReceiptEntity(
        id = id,
        purchaseDateTime = Instant.parse(this.purchaseDateTime),
        currency = this.currency,
        lines = mutableListOf(),
        user = user
    )

    receipt.lines = this.products.mapIndexed { index, dto ->
            dto.toEntity(
                receipt,
                products[index]
            )
        }
        .toMutableList()

    return receipt
}


fun ReceiptLineRequestDTO.toEntity(
    receipt: ReceiptEntity,
    product: ProductEntity
) : ReceiptLineEntity {
    return ReceiptLineEntity(
        id = 0, // ID will be generated by the database
        rawName = this.name,
        quantity = this.quantity,
        unit = this.unit,
        unitPrice = this.unitPrice,
        receipt = receipt,
        product = product
    )
}

