package com.d3v4d.receiptscanner.service

import com.d3v4d.receiptscanner.dto.request.ReceiptLineRequestDTO
import com.d3v4d.receiptscanner.dto.request.ReceiptRequestDTO
import com.d3v4d.receiptscanner.dto.request.Store
import com.d3v4d.receiptscanner.dto.response.ReceiptLineResponseDTO
import com.d3v4d.receiptscanner.dto.response.ReceiptResponseDTO
import com.d3v4d.receiptscanner.entity.ReceiptEntity
import com.d3v4d.receiptscanner.entity.ReceiptItemEntity
import com.d3v4d.receiptscanner.entity.StoreEntity
import com.d3v4d.receiptscanner.entity.UserEntity
import java.time.Instant

fun ReceiptEntity.toDTO(): ReceiptResponseDTO {
    return ReceiptResponseDTO(
        id = this.id,
        sourceScanId = this.sourceScan?.id,
        storeName = this.store?.name ?: "",
        purchaseDateTime = this.purchaseDateTime.toString(),
        currency = this.currency,
        lines = this.lines.map { it.toDTO() }
    )
}

fun ReceiptItemEntity.toDTO(): ReceiptLineResponseDTO {
    return ReceiptLineResponseDTO(
        id = this.id,
        name = this.name,
        quantity = this.quantity.toString(),
        unit = this.unit,
        unitPrice = this.unitPrice,
    )
}

fun ReceiptRequestDTO.toEntity(
    user : UserEntity,
    id: Long = 0,
): ReceiptEntity {
    val receipt = ReceiptEntity(
        id = id,
        purchaseDateTime = Instant.parse(this.purchaseDateTime),
        currency = this.currency,
        lines = mutableListOf(),
        user = user,
        store = this.store.toEntity(),
    )

    receipt.lines = this.lines.map { dto ->
            dto.toEntity(receipt)
        }
        .toMutableList()

    return receipt
}


fun ReceiptLineRequestDTO.toEntity(
    receipt: ReceiptEntity,
) : ReceiptItemEntity {
    return ReceiptItemEntity(
        id = 0, // ID will be generated by the database
        name = this.name,
        quantity = this.quantity,
        unit = this.unit,
        unitPrice = this.unitPrice,
        totalPrice = this.totalPrice,
        receipt = receipt,
    )
}

fun Store.toEntity(): StoreEntity {
    return StoreEntity(
        name = this.name,
        address = this.address,
        storeChain = this.chain,
    )
}

